// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBjG4qWihE1njI93NQW6jIYyZa57n40qE',
    appId: '1:704703255502:web:8ff456522e0cc8bab1919f',
    messagingSenderId: '704703255502',
    projectId: 'whatsapp-24711',
    authDomain: 'whatsapp-24711.firebaseapp.com',
    storageBucket: 'whatsapp-24711.appspot.com',
    measurementId: 'G-MTB0GW19H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGm4bLVUQtaKnDaaZ3Ve4gdkPVGqN7bUI',
    appId: '1:704703255502:android:31cfd96ed61c908db1919f',
    messagingSenderId: '704703255502',
    projectId: 'whatsapp-24711',
    storageBucket: 'whatsapp-24711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnS_11NGWzpUsphXDVWJurO1uzpw7l8Q',
    appId: '1:704703255502:ios:b8e8cea9bb345a62b1919f',
    messagingSenderId: '704703255502',
    projectId: 'whatsapp-24711',
    storageBucket: 'whatsapp-24711.appspot.com',
    iosClientId: '704703255502-9l8gsvfuh307g5t3u6or8cgrkpamao1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
